version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    allowed_updates:
      - match:
          update_type: "all"
    default_labels:
      - "dependency-update"
    default_reviewers:
          - "MMonrad"